name: time4play
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  salomon_bottom_bar: ^3.3.2
  http: ^1.3.0
  provider: ^6.1.2
  email_validator: ^3.0.0
  google_fonts: ^6.2.1
  intl: ^0.20.2
  flutter_launcher_icons: ^0.14.3  # Added for app icons
  badges: ^3.1.2
  visibility_detector: ^0.4.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/icons/logo.jpeg"  # Your main app icon
  adaptive_icon_background: "#0F172A"  # Background for adaptive icon (Android)
  # adaptive_icon_foreground: "lib/assets/icons/app_icon_foreground.png"  # Optional foreground

flutter:
  uses-material-design: true

  assets:
    - lib/assets/
    - lib/assets/images/
    - lib/assets/images/home/
    - lib/assets/images/venues/
    - lib/assets/icons/
