name: time4play
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  salomon_bottom_bar: ^3.3.2
  http: ^1.3.0
  email_validator: ^3.0.0
  google_fonts: ^6.2.1
  intl: ^0.20.2
  flutter_launcher_icons: ^0.14.3 
  badges: ^3.1.2
  visibility_detector: ^0.4.0+2
  flutter_native_splash: ^2.4.5
  lottie: ^3.3.1
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  google_sign_in: ^6.3.0
  cloud_firestore: ^5.6.6
  shared_preferences: ^2.5.3
  flutter_riverpod: ^2.6.1
  url_launcher: ^6.3.1
  permission_handler: ^12.0.0+1
  onesignal_flutter: ^5.3.0
  shimmer: ^3.0.0
  timeago: ^3.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/icons/logo2.jpg" # Your main app icon
  adaptive_icon_background: "#0F172A" # Background for adaptive icon (Android)
  # adaptive_icon_foreground: "lib/assets/icons/app_icon_foreground.png"  # Optional foreground

flutter:
  uses-material-design: true

  assets:
    - lib/assets/
    - lib/assets/icons/
    - lib/assets/images/
    - lib/assets/animations/
    - lib/assets/images/home/
    - lib/assets/images/venues/
    - lib/assets/images/companies/

  fonts:
    - family: WinkyRough
      fonts:
        - asset: lib/assets/fonts/WinkyRough-VariableFont_wght.ttf
        - asset: lib/assets/fonts/WinkyRough-Italic-VariableFont_wght.ttf
          style: italic

flutter_native_splash:
  color: "#FFFFFF" # White for light mode
  color_dark: "#0F172A" # Dark mode color
  image: lib/assets/icons/logo2.jpg
  image_dark: lib/assets/icons/logo2.jpg
  android: true
  ios: true
  android_12:
    image: lib/assets/icons/logo2.jpg
    icon_background_color: "#FFFFFF" # White for light mode
    icon_background_color_dark: "#0F172A" # Dark mode color
  web: false
