// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYgVrFhwWHZsRTas7IVl1PLPPRmir-ZD0',
    appId: '1:953296104788:web:03a603fe139a14ed89ecc1',
    messagingSenderId: '953296104788',
    projectId: 'time4play-5b336',
    authDomain: 'time4play-5b336.firebaseapp.com',
    databaseURL: 'https://time4play-5b336-default-rtdb.firebaseio.com',
    storageBucket: 'time4play-5b336.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZVHd0a3UNFKp3ID7cDT7axUQrYwePqnU',
    appId: '1:953296104788:android:b292fbcb689258c789ecc1',
    messagingSenderId: '953296104788',
    projectId: 'time4play-5b336',
    databaseURL: 'https://time4play-5b336-default-rtdb.firebaseio.com',
    storageBucket: 'time4play-5b336.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmSVQWn9Jl9fRRNqOwuc5Ynpgn2wEa6qc',
    appId: '1:953296104788:ios:6d877f2a9f3f0aef89ecc1',
    messagingSenderId: '953296104788',
    projectId: 'time4play-5b336',
    databaseURL: 'https://time4play-5b336-default-rtdb.firebaseio.com',
    storageBucket: 'time4play-5b336.firebasestorage.app',
    iosBundleId: 'com.example.time4play',
  );

}